# Generated by Django 4.2 on 2024-09-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(default='hola')),
                ('remitente', models.CharField(default='keyla', max_length=25)),
                ('destinatario', models.CharField(default='keyla', max_length=25)),
                ('fecha_y_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
